### ISSUE TITLE
docs: broken link in README Tutorials...

### ISSUE THREAD

**Issue by pareyesv** [scikit-mobility/tutorials#4]
In the [Tutorials](https://github.com/scikit-mobility/tutorials) README file, the link to [Master on Big Data Analytics & Social Mining](https://www.masterbigdata.it/) is broken.

**Comment by pareyesv** [comment]
Oops... It was a just a momentary problem.
The link is properly working right now.

**Comment by pareyesv** [comment]
OK. My fault. Sorry. This is the broken link:
https://appliedmldays.org/workshops/human-mobility-analysis-and-simulation-with-python

And I think this is the right one:
https://appliedmldays.org/events/amld-epfl-2020/workshops/human-mobility-analysis-and-simulation-with-python

**Comment by jonpappalord** [comment]
It seems they moved the page to another link. Just fixed. 
Thanks, @pareyesv.
